### ISSUE TITLE
FHIRExportwithAnonymization - Fail when adding "IntegrationStorageAccount" to arm_template.parameters.json

### ISSUE THREAD

**Issue by cyberuna** [microsoft/health-architectures#11]
![Error](https://user-images.githubusercontent.com/50457372/92425330-84709280-f14c-11ea-8b96-148ab12e8615.PNG)

**Comment by corygstevenson** [comment]
I'll take a look at this.

**Comment by cyberuna** [comment]
![image](https://user-images.githubusercontent.com/50457372/93720905-ca1c5a80-fb51-11ea-8d1d-dc02b99287f1.png)

Downloaded the latest files and tried deploying, getting this error. Could you please check?

**Comment by corygstevenson** [comment]
I have not been able to reproduce this error. However, I did find two other items which needed updated. 1) spelling mistake in a powershell script and 2) missing instructions for when deploying powershell with Integrations Accounts preset.
