### ISSUE TITLE
Bash Scripts Not Stopping on Sub-shell Failures

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/health-architectures#23]
I found this issue while working with `deployhl72fhir.bash` and confirmed that the same issue exists in at least one more `.bash` script. The start of the scripts has `set -euo pipefail`, however this is not honored in the sub-shells. This results in confusing behavior, like scripts saying they succeeded when they actually failed.

I don't have time for a PR now (apologies), but wanted to submit this for tracking. Probably the easiest solution is to implement what is suggested [here](https://unix.stackexchange.com/a/600212) and require Bash >= 4.4 since Bash 4+ is required already.

Example of what the user sees when this issue arises:
![image](https://user-images.githubusercontent.com/753437/95666009-6ced4680-0b0a-11eb-8477-7edb883a25df.png)

**Comment by mattpasco-microsoft** [comment]
Ideally this should be done in ARM, and this script could just be a wrapper around group deploy

**Comment by mattpasco-microsoft** [comment]
Using the az cli causes deployment failures as the resources are not fully provisioned, causing subsequent commands to fail. The process of prompting the user for 12 variables is tedious.

**Comment by daemel** [comment]
Bash shells are being factored out during backlog sprints.   Thanks for the notes, we will address the use of sub-shells as quickly as we can
