### ISSUE TITLE
We can't use Validator endpoint

### ISSUE THREAD

**Issue by fao001** [microsoft/health-architectures#29]
Hello, I'm trying to us configure the services endpoint using the documentation, but the when i run the docker command file (using windows as container) the command didn't work. when change to Linux container, the command run, but when i try to run this command => docker run -it --rm -p 8080:8080 myfhirvalidator-svc ... an error is shown and the image never run....

Also, when running the validator downloaded from here http://hl7.org/fhir/validator/ some of the profiles
i've being validating say "This is not a resource" or it does validate and throw errors like "Property not valid on
us-core...". Any help would be highly appretiated.

There are any consideration that i have to know.... in order to run this properly?

Regards !

**Comment by daemel** [comment]
There is a blog post on running validator as a container instance here - https://microsoft.github.io/health-architectures/FHIR-Validator-Container-Instance.html.  Please give the container instance a try - if you want to run as a container, we do recommend a *nix variety with at least 16GB of RAM.  If none of these options work, please let us know more about the error.
