### ISSUE TITLE
Incorrect API path in Readme

### ISSUE THREAD

**Issue by mohannadh** [microsoft/health-architectures#61]
I'm not sure if I am confusing 2 APIs but as I was following the instructions to[ set up the Participant Filter Post-Processor](https://github.com/microsoft/health-architectures/tree/master/FHIR/FHIRProxy#how-the-participant-post-processor-works-) I kept getting a 404 when trying to [link my user to a fhir resource](https://github.com/microsoft/health-architectures/tree/master/FHIR/FHIRProxy#linking-users-in-participant-roles-to-fhir-resources-). 

The instructions said to call the API endpoint following the path
`https://<your fhir proxy url>/api/manage/link/<ResourceName>/<ResourceID>?name=<user principal name>.`

however looking through the [code](https://github.com/microsoft/health-architectures/blob/master/FHIR/FHIRProxy/FHIRProxy/SecureLink.cs#L45) it looks like the correct path is
`https://<your fhir proxy url>/api/manage/link/<ResourceName>/<ResourceID>/<user principal name>`

Are the readme instructions incorrect?

**Comment by corygstevenson** [comment]
@erikhoward and @daemel Can you review this issue? If it is a doc issue, can we get @v-pbartley to validate and fix.

Thanks.

**Comment by daemel** [comment]
I will take this

**Comment by daemel** [comment]
closed with correction
