### ISSUE TITLE
Linking Users to Roles (FHIR Administrator Role)

### ISSUE THREAD

**Issue by chegemr** [microsoft/health-architectures#72]
Hi,

We are running into issues finalizing the SMART Proxy setup for external users within the Azure API for FHIR. We have created roles and are at the stage of Linking Users in the Participant Roles to FHIR Resources but are getting a 404 error. Can you please explain where one would grant the FHIR Administrative Role to complete the set-up.

health-architectures/FHIR/FHIRProxy at master · microsoft/health-architectures · GitHub

Kind Regards,
Moses Chege
Solution Architect , CHC

**Comment by daemel** [comment]
please reference https://github.com/microsoft/fhir-proxy
