### ISSUE TITLE
can not Authorize FHIRServerProxy-1

### ISSUE THREAD

**Issue by imrago-medxnote** [microsoft/health-architectures#85]
After running the deployhl72fhir.bash script everything is set up.

After that FHIRServerProxy-1  API Connection is in Error state ( This connection is not authenticated )

When attempting to Authorize I am directed to a login form for my credentials and getting this error message after logging in:

AADSTS90008: The user or administrator has not consented to use the application with ID '3648ca46-8d1e-4d62-8cde-27c00e70b03b'(https://sfp-proxy18447.azurewebsites.net). This happened because application is misconfigured: it must require access to Microsoft Graph by specifying at least 'Sign in and read user profile' permission.

In the documentation it is stated :

%%%%%
Goto the resource group that contains the deployed HL7toFHIR workflow
Find the FHIRServerProxy-1 API Connection and click on it
Click on Edit API Connection
Enter a Display name of FHIR Server Proxy
Click Authorize
Enter the Credentials for the user account, group or service principal from step #4
Click Save
%%%%%

3648ca46-8d1e-4d62-8cde-27c00e70b03b was created by the scripts and the values added to the key vault.  

How can be this issue resolved?  Where should I "Enter the Credentials for the user account, group or service principal from step #4"?

**Comment by daemel** [comment]
looking into this

**Comment by imrago-medxnote** [comment]
I had granted Admin consent for the mentioned Enterprise application created by the script in the Permissions section:
'3648ca46-8d1e-4d62-8cde-27c00e70b03b'(https://sfp-proxy18447.azurewebsites.net)

Now after clicking Authorize in  FHIRServerProxy-1 API Connection  and logging in, I am getting this new error : 

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '3648ca46-8d1e-4d62-8cde-27c00e70b03b'.

Where should be the reply URL changed and to what?

**Comment by daemel** [comment]
> I had granted Admin consent for the mentioned Enterprise application created by the script in the Permissions section: '3648ca46-8d1e-4d62-8cde-27c00e70b03b'(https://sfp-proxy18447.azurewebsites.net)
> 
> Now after clicking Authorize in FHIRServerProxy-1 API Connection and logging in, I am getting this new error :
> 
> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '3648ca46-8d1e-4d62-8cde-27c00e70b03b'.
> 
> Where should be the reply URL changed and to what?

There should be 2 reply url's in your app where $fphost = name of your proxy function app and $resourceGroupLocation = name of your region (without spaces)


https://"$fphost"/.auth/login/aad/callback 
https://logic-apis-"$resourceGroupLocation".consent.azure-apim.net/redirect

**Comment by imrago-medxnote** [comment]
Thank you, that helped.

The first url was already present (https://"$fphost"/.auth/login/aad/callback ), added the second one and it started working.
